### ISSUE TITLE
Sequence with ambiguous (unlawful) nucleotides 

### ISSUE THREAD

**Issue by virologist** [WilsonImmunologyLab/Librator#1]
Hi, Patrick and Lei,

Librator was recommended by my supervisor last week. It's really a very promising tool to do flu research. 

When I input the HA sequences collected from the open databases, this warning message is really annoying. I cannot close or skip it, even move forward to the next step. For true, these sequences have some ambiguous (unlawful) nucleotides. **Can you replace this pop-out window with a log file?**
![Snipaste_2021-05-06_17-04-19](https://user-images.githubusercontent.com/54756814/117272122-73b81e00-ae8d-11eb-8000-2257b7193607.png)

Sometimes, sequences are collected from public databases with ambiguous or missing nucleotides.  It's a headache process to carefully manipulate the ambiguous and missing parts for further _in silicon_ analysis. e.g. PAML cannot tolerate the ambiguous or incomplete codon at all, which means only A, T, G, and C are acceptable. In this case, you must correct the ambiguous and incomplete parts if you want to use all available sequences. We have written a script to try to figure out the ambiguous and incomplete codon (more detail: https://github.com/virologist/ambiguous_base_v2). 

Back to Librator, **can you add some script modules to clean (or "correct") the sequences with a few (like, <1% or 5%) ambiguous codons after input (if Librator did not have)?** 

The workflow running like this: 
1). input the sequences and detect the ambiguous characters and export the log file; 
2). align and clean (or correct) the ambiguous parts; 
3). enjoy other Librator functions

Thanks,
Yang

**Comment by LeiLi-Uchicago** [comment]
Hello Yang,

Thank you so much for pointing out this inconvenience！I just tried to import sequences from your repo (https://github.com/virologist/ambiguous_base_v2) and yes, the pop-up window is really annoying! 

I apologize for not testing this function on more datasets. I will do a quick fix on this function according to your comments for now, and then think about a better solution later.

Again, thank you so much for your comments! Please feel free to let me know if there is anymore issues! 

Best,
Lei Li

**Comment by LeiLi-Uchicago** [comment]
Just made a quick fix. I replaced the annoying pop-up window by a text editor. All error information will be displayed in the text editor while the main UI is still functional. The text editor will be popped up when new error detected. If users keep it open, the error message will keep updated.

<img width="1911" alt="Screen Shot 2021-05-06 at 10 49 03 AM" src="https://user-images.githubusercontent.com/4589583/117327938-c0353680-ae58-11eb-8f45-61379fd7ee4b.png">

I will update the MAC version later today and update the Windows version tonight (I forgot to bring Windows machine to office).  

Thanks again for your comments!

**Comment by LeiLi-Uchicago** [comment]
I would like to close it for now but will definitely think about a better solution for those ambiguous nucleotides as you suggested. 
Thank you so much for your suggestion and please feel free to let me know if there is any other issues/BUGs!
